# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uctl < Formula
  desc "Uctl is a lightweight command-line interface to work with Unionai Cloud"
  homepage "https://docs.union.ai/"
  version "0.1.12"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/unionai/uctl/releases/download/v0.1.12/uctl_Darwin_arm64.tar.gz"
      sha256 "ab8e6d017da55f0dc14af2a3b8e26b70dd1a93239bbf8022ec8e5eeb915d154e"

      def install
        bin.install "uctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/unionai/uctl/releases/download/v0.1.12/uctl_Darwin_x86_64.tar.gz"
      sha256 "b40c2d49345237cf2f4958a11070263dc90e5adea8ea81483be0a8840b7e6438"

      def install
        bin.install "uctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unionai/uctl/releases/download/v0.1.12/uctl_Linux_arm64.tar.gz"
      sha256 "7ae4e62040f9f8aec912a0429cd892bd4fa8e83a45832dd6862975d395e23ed1"

      def install
        bin.install "uctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/unionai/uctl/releases/download/v0.1.12/uctl_Linux_x86_64.tar.gz"
      sha256 "56e418919aeaea178d0375fc51c8116518b0ea14b6ae7483485d2239506c0c93"

      def install
        bin.install "uctl"
      end
    end
  end
end
